name: Publish to npm with provenance
on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'  # tag like v1.0.5

permissions:
  id-token: write   # required for provenance
  contents: read

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: '22'
          registry-url: 'https://registry.npmjs.org'

      - name: Install
        run: npm install --ignore-scripts

      - name: Build
        run: npm run build --if-present

      - name: Show GH context
        run: |
          echo "REPO=$GITHUB_REPOSITORY"           # should be cortex-one-platform/caitai-test-framework
          echo "WORKFLOW_REF=$GITHUB_WORKFLOW_REF" # includes .github/workflows/<your-file>
          echo "WORKFLOW=$GITHUB_WORKFLOW"         # friendly name

      - name: Verify token can publish (throwaway)
        run: |
          set -euxo pipefail
          echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > ~/.npmrc
          tmpdir=$(mktemp -d)
          cd "$tmpdir"
          npm init -y
          npm pkg set name="@therealwillesclusa/repro-$(date +%s)" version="1.0.0"
          echo 'module.exports={}' > index.js
          npm publish --access public --tag test
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Auth to npm
        run: |
          echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > ~/.npmrc
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}  # add in repo settings

      - name: Publish (provenance)
        run: npm publish --access public --tag latest --provenance
