name: Publish to npm with provenance
on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'  # tag like v1.0.5

permissions:
  id-token: write   # required for provenance
  contents: read

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: '22'
          registry-url: 'https://registry.npmjs.org'

      - name: Install
        run: |
          if [ -f package-lock.json ]; then
            echo "Using npm ci";
            npm ci --ignore-scripts;
          else
            echo "No package-lock.json found; using npm install";
            npm install --ignore-scripts;
          fi

      - name: Build
        run: npm run build --if-present

      - name: Show GH context
        run: |
          echo "REPO=$GITHUB_REPOSITORY"           # should be cortex-one-platform/caitai-test-framework
          echo "WORKFLOW_REF=$GITHUB_WORKFLOW_REF" # includes .github/workflows/<your-file>
          echo "WORKFLOW=$GITHUB_WORKFLOW"         # friendly name

      - name: Auth to npm
        run: |
          echo "registry=https://registry.npmjs.org/" > "$NPM_CONFIG_USERCONFIG"
          echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" >> "$NPM_CONFIG_USERCONFIG"
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}  # add in repo settings

      - name: Sanity whoami
        run: |
          npm whoami
          npm config get userconfig
          head -n 5 "$(npm config get userconfig)"

      - name: Publish (provenance)
        run: npm publish --access public --tag latest --provenance
